// <auto-generated />
using System;
using Events.model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evant.model.Migrations
{
    [DbContext(typeof(EventContext))]
    [Migration("20231120162017_firstMigration")]
    partial class firstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Events.model.Model.Hall", b =>
                {
                    b.Property<int>("HallId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HallId"), 1L, 1);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContainSites")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNamber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HallId");

                    b.ToTable("Hall");
                });

            modelBuilder.Entity("Events.model.Model.InventionEvent", b =>
                {
                    b.Property<int>("InventionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventionEventId"), 1L, 1);

                    b.Property<string>("CountPeople")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HallId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvatorId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Payment")
                        .HasColumnType("int");

                    b.HasKey("InventionEventId");

                    b.ToTable("InventionEvent");
                });

            modelBuilder.Entity("Events.model.Model.InventionMenu", b =>
                {
                    b.Property<int>("InventionEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InventionEventId"), 1L, 1);

                    b.Property<int>("CountProduct")
                        .HasColumnType("int");

                    b.Property<int?>("ManaId")
                        .HasColumnType("int");

                    b.HasKey("InventionEventId");

                    b.ToTable("InventionMenu");
                });

            modelBuilder.Entity("Events.model.Model.Inviter", b =>
                {
                    b.Property<int>("InviterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InviterId"), 1L, 1);

                    b.Property<string>("InviterMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InviterPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("InviterId");

                    b.ToTable("Inviter");
                });

            modelBuilder.Entity("Events.model.Model.Menu", b =>
                {
                    b.Property<int>("ManaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ManaId"), 1L, 1);

                    b.Property<string>("Kashrut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ManaStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ManaId");

                    b.ToTable("Menu");
                });
#pragma warning restore 612, 618
        }
    }
}
